/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthHasAddButtonRouteRouteImport } from './routes/_auth/_hasAddButton/route'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as AuthHasAddButtonAppRouteRouteImport } from './routes/_auth/_hasAddButton/app/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthHasAddButtonAppIndexRouteImport } from './routes/_auth/_hasAddButton/app/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHasAddButtonRouteRoute = AuthHasAddButtonRouteRouteImport.update({
  id: '/_hasAddButton',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthHasAddButtonAppRouteRoute =
  AuthHasAddButtonAppRouteRouteImport.update({
    id: '/app',
    path: '/app',
    getParentRoute: () => AuthHasAddButtonRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHasAddButtonAppIndexRoute =
  AuthHasAddButtonAppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthHasAddButtonAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/app': typeof AuthHasAddButtonAppRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthHasAddButtonAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthHasAddButtonAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/_hasAddButton': typeof AuthHasAddButtonRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/_hasAddButton/app': typeof AuthHasAddButtonAppRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/_hasAddButton/app/': typeof AuthHasAddButtonAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/app' | '/api/auth/$' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/api/auth/$' | '/app'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/_hasAddButton'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_auth/_hasAddButton/app'
    | '/api/auth/$'
    | '/_auth/_hasAddButton/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_hasAddButton': {
      id: '/_auth/_hasAddButton'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthHasAddButtonRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/_hasAddButton/app': {
      id: '/_auth/_hasAddButton/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthHasAddButtonAppRouteRouteImport
      parentRoute: typeof AuthHasAddButtonRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_hasAddButton/app/': {
      id: '/_auth/_hasAddButton/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthHasAddButtonAppIndexRouteImport
      parentRoute: typeof AuthHasAddButtonAppRouteRoute
    }
  }
}

interface AuthHasAddButtonAppRouteRouteChildren {
  AuthHasAddButtonAppIndexRoute: typeof AuthHasAddButtonAppIndexRoute
}

const AuthHasAddButtonAppRouteRouteChildren: AuthHasAddButtonAppRouteRouteChildren =
  {
    AuthHasAddButtonAppIndexRoute: AuthHasAddButtonAppIndexRoute,
  }

const AuthHasAddButtonAppRouteRouteWithChildren =
  AuthHasAddButtonAppRouteRoute._addFileChildren(
    AuthHasAddButtonAppRouteRouteChildren,
  )

interface AuthHasAddButtonRouteRouteChildren {
  AuthHasAddButtonAppRouteRoute: typeof AuthHasAddButtonAppRouteRouteWithChildren
}

const AuthHasAddButtonRouteRouteChildren: AuthHasAddButtonRouteRouteChildren = {
  AuthHasAddButtonAppRouteRoute: AuthHasAddButtonAppRouteRouteWithChildren,
}

const AuthHasAddButtonRouteRouteWithChildren =
  AuthHasAddButtonRouteRoute._addFileChildren(
    AuthHasAddButtonRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthHasAddButtonRouteRoute: typeof AuthHasAddButtonRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthHasAddButtonRouteRoute: AuthHasAddButtonRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
